version: '3'
# each container that launch is a service:
services:
  database:
    image: postgres:12
    container_name: database
    hostname: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_db
    volumes:
      #- pgdata:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:54321:5432"
    #networks:
    #  - localnet

#networks:localnet:   driver: bridge


